import "server-only";
import { openai } from "@ai-sdk/openai";
import { generateText, Output } from "ai";
import { z } from "zod";

// ai@7 has no generateObject — structured output is generateText's `output`
// option (node_modules/ai/docs/03-ai-sdk-core/10-generating-structured-data.mdx).
export const ANALYSIS_MODEL = "gpt-5.4-mini";

// AGENTS.md §19: derived server-side, not requested from the model.
export const ANALYSIS_DISCLAIMER =
  "This political framing and sentiment analysis is generated by AI and represents an estimate, not an objective fact.";

const PERCENTAGE_SUM_TOLERANCE = 1;

export const AnalysisSchema = z
  .object({
    summary: z.string().min(1),
    sentimentScore: z.number().min(-1).max(1),
    sentimentLabel: z.enum(["positive", "neutral", "negative"]),
    politicalFramingLabel: z.enum(["left", "center", "right", "mixed", "unclear"]),
    leftPercentage: z.number().min(0).max(100),
    centerPercentage: z.number().min(0).max(100),
    rightPercentage: z.number().min(0).max(100),
    confidence: z.number().min(0).max(1),
    framingNotes: z.string().min(1),
    loadedTerms: z.array(z.string()),
  })
  .refine(
    (data) =>
      Math.abs(data.leftPercentage + data.centerPercentage + data.rightPercentage - 100) <=
      PERCENTAGE_SUM_TOLERANCE,
    { message: "leftPercentage + centerPercentage + rightPercentage must sum to ~100" },
  );

export type AnalysisOutput = z.infer<typeof AnalysisSchema>;

const SYSTEM_PROMPT = `You are a media bias and sentiment analysis assistant for a news aggregation product.

Analyze the given news article using ONLY the evidence in the article text itself — never infer political framing from the publication's name or reputation.

Rules:
- Write a neutral, factual summary (2-4 sentences) that strips out partisan framing.
- Judge the sentiment of the article's own tone (not the sentiment of the events described): sentimentLabel is positive, neutral, or negative, with a matching sentimentScore from -1 (very negative) to 1 (very positive).
- Estimate political framing from word choice, sourcing, emphasis, and framing choices actually present in the text. leftPercentage, centerPercentage, and rightPercentage must each be 0-100 and sum to exactly 100.
- politicalFramingLabel should match whichever percentage is highest, EXCEPT: use "mixed" when the top two percentages are close, and use "unclear" when the evidence for any framing is genuinely weak — and keep confidence low whenever you choose "mixed" or "unclear".
- confidence (0 to 1) reflects how confident you are in the framing and sentiment estimate overall.
- loadedTerms lists emotionally charged, persuasive, or biased words/phrases that actually appear in the article text (return an empty array if none stand out).
- framingNotes (1-3 sentences) explains which specific wording or framing choices informed your assessment.`;

function buildPrompt(title: string, rawText: string): string {
  return `Title: ${title}\n\nArticle:\n${rawText}`;
}

export async function analyzeArticleText(title: string, rawText: string): Promise<AnalysisOutput> {
  const { output } = await generateText({
    model: openai(ANALYSIS_MODEL),
    system: SYSTEM_PROMPT,
    prompt: buildPrompt(title, rawText),
    output: Output.object({ schema: AnalysisSchema }),
  });
  return output;
}
